### ISSUE TITLE
Stuff that's sus

### ISSUE THREAD

**Issue by faddat** [LambdaIM/lambdavm#34]
* dragonberry unpatched
* ibc v4.0.0-rc0 was never even a release, let alone secure
* users cannot move funds from lambda to osmosis
* evm code did not import ethermint, confounding an audit because we don't know how to verify which version of ethermint was used
* last commit is sept 20
* numerous dependabot PR's unmerged and unclosed
* likely a zero attribution copy of Ethermint from evmos/ethermint
* ethermint license does require attribution, afaik
* https://github.com/steveliupai <- committer for code in this repo is a totally fresh github user.

**Comment by steveliupai** [comment]
@faddat Thank you for your notes. Lambdavm is a forked version of ethermint, we don't modify any logic code except bech32 format and we are developing dapps now and will add more modules for our own chain. [dapp](https://app.lambda.im/)

For users mentioned about move funds failure, we have added informations [here](https://docs.lambda.im/users/dapp/ibc.html) to increase gas limit manually to ensure funds been transferred successfully. Currently relayer works well and transfer only takes few seconds.

**Comment by steveliupai** [comment]
@faddat Could u tell us how to meet the attribution for ethermint license need?
